#
# Makefile
#
# Computer Science 50
# Problem Set 3
#

copy: copy.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o copy copy.c -lcs50 -lm

clean:
	rm -f *.o a.out core copy log.txt

whodunit: whodunit.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o whodunit whodunit.c -lcs50 -lm
